server:
  port: 8080
spring:
  application:
    name: rddp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ap?useSSL=false&serverTimezone=UTC
    username: root
    password: XINhaoroot

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.me.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true